######################################################################
# Automatically generated by qmake (1.04a) Mon May 10 14:16:16 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += interact.h qpconfig.h xqpdebug.h
SOURCES += interact.cc main.cc qpconfig.cc xqpdebug.cc
